### PR TITLE
Grunt to npm

### LINKED ISSUE #36: Replace Grunt with NPM scripts

### PR DESCRIPTION
**Pull request by shaungrady**
Resolves #36.

Adds the following npm scripts:

- `test` — Starts Karma, runs the Jasmine tests in PhantomJS
- `build` — Runs tests, transpiles Coffee, prepends banner comment
- `start` — Runs build continuously
- `dist` — Runs build, uglifies, prepends minibanner

### CODE REVIEW

**Comment by shaungrady** [comment]
Since `grunt-bump` is gone, when you want to bump the version, you use `npm version` instead. E.g., `npm version patch`. [Documentation](https://docs.npmjs.com/cli/version)

**Comment by shaungrady** [comment]
Any comments, questions, concerns on this?

**Comment by robtarr** [comment]
Going to try to look at it a bit more tonight. I had a few issues getting it going, but I think it looks good overall.

**Comment by shaungrady** [comment]
Issues? Old version of Node?

**Comment by robtarr** [comment]
I made a few changes, rebased and merged this in. Thanks!

**Pull request closed without merging**
